data/regions.csv
db/migrate/20191118164814_update_user_ref_in_buyer_details.rb
db/migrate/20200318140756_merge_quick_search_and_contract_name.rb
db/migrate/20200430131751_update_building_types_in_the_db.rb
db/migrate/20200701092909_add_personnel_to_existing_service_hours.rb
db/migrate/20200714140233_add_external_area_to_existing_buildings.rb
db/migrate/20200716151216_remove_external_area_from_procurement_building_service.rb
db/schema.rb
lib/tasks/static.rake

Database schema is only used for running specs. db:migrate is not run on deployment as responsibility for this task will remain with the crown-marketplace application

Restore static data task and update test database schema

---

pipeline_pre_build_tests.sh

- Add key in script so Nodejs can install
One of the dependancies used in the instillation for nodejs had an update on Friday 19th March which caused the issue. I added this line to the script as it added the missing key which was stopping the instillation. I've tested this in sandbox and it deploys successfully.

FMFR-726 - Fix issue with failing deployments

---

config/initializers/active_storage.rb

We need to add a load balancer update.
We need to add OR /legacy-storage*
This is so that documents can be downloaded properly from the admin section

FMFR-839 - Add active storage prefix

---

Gemfile.lock

Fix issue where nokogiri could not upgrade properly

---

app/controllers/base/registrations_controller.rb
app/controllers/base/sessions_controller.rb
app/controllers/base/users_controller.rb
app/controllers/legal_services/admin/sessions_controller.rb
app/controllers/legal_services/admin/users_controller.rb
app/controllers/legal_services/registrations_controller.rb
app/controllers/legal_services/sessions_controller.rb
app/controllers/legal_services/users_controller.rb
app/controllers/management_consultancy/admin/sessions_controller.rb
app/controllers/management_consultancy/admin/users_controller.rb
app/controllers/management_consultancy/registrations_controller.rb
app/controllers/management_consultancy/sessions_controller.rb
app/controllers/management_consultancy/users_controller.rb
app/controllers/supply_teachers/admin/sessions_controller.rb
app/controllers/supply_teachers/admin/users_controller.rb
app/controllers/supply_teachers/sessions_controller.rb
app/controllers/supply_teachers/users_controller.rb
app/views/home/cookie_policy.html.erb
app/views/shared/users/_confirm_new.html.erb
config/locales/en.yml

- Move shared logic into shared controller
- Hide email param from URL by putting it in the cookies
- Move shared logic into shared controller (again)
From an ITHC, we had already changed the email in one place to be stored in the browser cookies.
I have extended this to the email that is still shown too.
I will do tests in sandbox first before merging this branch.

FMFR-1129 - Remove email from URL

---

Gemfile
Gemfile.lock

- Remove `smarter_csv` as this is used for downloading address which is not part of legacy
- Remove `amoeba` as this is used for dupliacting procurements which is not part of legacy

Remove Crown Marketplace FM dependencies

---

Gemfile
Gemfile.lock
app/controllers/legal_services/suppliers_controller.rb
app/controllers/management_consultancy/suppliers_controller.rb
app/controllers/supply_teachers/branches_controller.rb
app/controllers/supply_teachers/downloads_controller.rb
spec/controllers/management_consultancy/suppliers_controller_spec.rb
spec/controllers/supply_teachers/downloads_controller_spec.rb

The purpose of this PR is to change from using `cancan` to `cancancan` due to the former no longer being supported anymore. as `cancancan` is based off of `cancan` we do not require any additional changes and we have tests for permissions which verify that they all still working as expected.
This led to some issues when downloading spreadsheets so I had to make a few more updates to make sure the spreadsheets can be downloaded. I was able to work out [what caused the issue](https://github.com/CanCanCommunity/cancancan/pull/495/files#diff-bc7f860bbee1c5954a600d27386afe3aa1abb5e305c7ae36c5b1f838f1f313dd) but so far have been unable to determine why it causes it.
While doing this I found that an admin file could be downloaded without the restriction that the user needed to be an admin and so …

Change to `cancancan` as `cancan` is no longer supported

---

config/environments/production.rb

Ticket: [FMFR-1126](https://crowncommercialservice.atlassian.net/browse/FMFR-1126)
See [actiondispatch-hostauthorization](https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization) for details.
This should prevents against DNS rebinding and other `Host` header attacks.
The following environment variables need to be set:
Environment | `/Environment/global/ENVIRONMENT_HOST` value
-- | --
cmpdev | `.cmp.cmpdev.crowncommercial.gov.uk`
sandbox | `.cmp.cmp-sandbox.crowncommercial.gov.uk`
preview | `.marketplace.preview.crowncommercial.gov.uk`
production | `.marketplace.service.crowncommercial.gov.uk`

FMFR-1126 - Add config to limit the name of hosts in production

---

app/views/management_consultancy/rm6187/passwords/new.html.erb
spec/controllers/legal_services/rm3788/admin/passwords_controller_spec.rb
spec/controllers/legal_services/rm3788/admin/sessions_controller_spec.rb
spec/controllers/legal_services/rm3788/passwords_controller_spec.rb
spec/controllers/legal_services/rm3788/registrations_controller_spec.rb
spec/controllers/legal_services/rm3788/sessions_controller_spec.rb
spec/controllers/legal_services/rm3788/users_controller_spec.rb
spec/controllers/management_consultancy/rm6187/admin/passwords_controller_spec.rb
spec/controllers/management_consultancy/rm6187/admin/sessions_controller_spec.rb
spec/controllers/management_consultancy/rm6187/admin/users_controller_spec.rb
spec/controllers/management_consultancy/rm6187/passwords_controller_spec.rb
spec/controllers/management_consultancy/rm6187/registrations_controller_spec.rb
spec/controllers/management_consultancy/rm6187/sessions_controller_spec.rb
spec/controllers/management_consultancy/rm6187/users_controller_spec.rb
spec/controllers/supply_teachers/rm3826/admin/passwords_controller_spec.rb
spec/controllers/supply_teachers/rm3826/admin/sessions_controller_spec.rb
spec/controllers/supply_teachers/rm3826/passwords_controller_spec.rb
spec/controllers/supply_teachers/rm3826/sessions_controller_spec.rb

This was spotted on Rollbar: https://rollbar.com/crowncommercial/Digital-Foundation/items/969/?utm_campaign=new_item&utm_medium=email&utm_source=rollbar-notification&utm_content=control
Fix issue where users can't reset their password and add tests to make sure it has worked

Fix issue where users can't reset their password

---

.github/workflows/rubyonrails.yml

I’ve updated the GitHub actions so that when we do a release to preview/production we run the full feature test suite instead of just a smaller set of tests.
We run a smaller set of feature tests to save time on development, but before we do a release we should check that everything is working as these feature test cover nearly all of the application.

Run all feature tests on release 

---

app/helpers/supply_teachers/rm6238/suppliers_helper.rb
app/services/supply_teachers/rm6238/admin/data_import/generate_pricing.rb
spec/helpers/supply_teachers/rm6238/suppliers_helper_spec.rb

Ticket: [FMR-1202](https://crowncommercialservice.atlassian.net/browse/FMFR-1202)
Fix issue where percentage prices were not imported correctly.
In excel, percentages are stored as decimal points (0.25 = 25%). Therefor, for our rates model we need to times this by 10,000, instead of 100 which is what was happening. For example, 0.025 -> 250 -> 2.5%.

FMFR-1202 - Fix issue where percentage prices were not imported correctly

---

app/controllers/supply_teachers/rm6238/suppliers_controller.rb
app/helpers/supply_teachers/rm6238/suppliers_helper.rb
app/models/supply_teachers/rm6238/journey/education_technology_platform_vendors.rb
app/models/supply_teachers/rm6238/journey/managed_service_provider.rb
app/views/supply_teachers/rm6238/suppliers/_education_technology_platform_vendor.html.erb
app/views/supply_teachers/rm6238/suppliers/_master_vendor.html.erb
app/views/supply_teachers/rm6238/suppliers/education_technology_platform_vendors.html.erb
config/locales/views/supply_teachers.en.yml
config/routes.rb
spec/controllers/supply_teachers/rm6238/suppliers_controller_spec.rb
spec/helpers/supply_teachers/rm6238/suppliers_helper_spec.rb
spec/models/supply_teachers/rm6238/journey/education_technology_platform_vendors_spec.rb
spec/models/supply_teachers/rm6238/journey/managed_service_provider_spec.rb

Ticket: [FMR-1148](https://crowncommercialservice.atlassian.net/browse/FMFR-1148)
In this commit I have added the results page for the Education Technology Platform vendors.
I have also added specs for the new models and controllers created as part of this journey.
I will add the feature tests in the next commit now that the managed service providers journey is completed.

FMFR-1148 - Add the education tech platforms results

---

app/controllers/supply_teachers/branches_controller.rb
app/models/supply_teachers/spreadsheet.rb
spec/controllers/supply_teachers/rm3826/branches_controller_spec.rb
spec/controllers/supply_teachers/rm6238/branches_controller_spec.rb
spec/models/supply_teachers/spreadsheet_spec.rb

Ticket: [FMR-1204](https://crowncommercialservice.atlassian.net/browse/FMFR-1204)
In this commit I have added the ability to download the spreadsheet of the supplier results. It turns out that the spreadsheet we generate is identical to the one for the previous framework so we didn’t need to create any new code (just share the code).
In the next PR I will add the feature tests for this part of the supplier journey.

FMFR-1204 - Add supplier spreadsheet

---

app/models/legal_services/rm6240.rb
app/models/legal_services/rm6240/jurisdiction.rb
app/models/legal_services/rm6240/lot.rb
app/models/legal_services/rm6240/position.rb
app/models/legal_services/rm6240/rate.rb
app/models/legal_services/rm6240/service.rb
app/models/legal_services/rm6240/service_offering.rb
app/models/legal_services/rm6240/supplier.rb
config/initializers/inflections.rb
data/legal_services/rm6240/jurisdictions.csv
data/legal_services/rm6240/lots.csv
data/legal_services/rm6240/position.csv
data/legal_services/rm6240/services.csv
db/migrate/20220725141935_add_legal_services_tables.rb
db/schema.rb
spec/factories/legal_services/rm6240/rate.rb
spec/factories/legal_services/rm6240/service_offering.rb
spec/factories/legal_services/rm6240/supplier.rb
spec/models/legal_services/rm6240/jurisdiction_spec.rb
spec/models/legal_services/rm6240/lot_spec.rb
spec/models/legal_services/rm6240/position_spec.rb
spec/models/legal_services/rm6240/rate_spec.rb
spec/models/legal_services/rm6240/service_offering_spec.rb
spec/models/legal_services/rm6240/service_spec.rb
spec/models/legal_services/rm6240/supplier_spec.rb

Ticket: [FMR-1209](https://crowncommercialservice.atlassian.net/browse/FMFR-1209)
We are creating a new framework for legal services. In this commit I have created the models in the database for the new legal service framework. There are some changes from the previous framework, most notebally:
- Using a single service offerings model to determine of the supplier can offer the service in the jurisdiction
- Storing the rates as an integer to avoid issues with floats
Though we don’t have an upload yet, I have created/copied specs based on the previous framework to make sure it is all working.

FMFR-1209 - Create legal services RM6240 models

---

app/controllers/legal_services/admin/frameworks_controller.rb
app/controllers/management_consultancy/admin/frameworks_controller.rb
app/controllers/supply_teachers/admin/frameworks_controller.rb
app/models/ability.rb
app/models/user.rb
config/application.rb
config/routes.rb
spec/controllers/legal_services/admin/frameworks_controller_spec.rb
spec/controllers/management_consultancy/admin/frameworks_controller_spec.rb
spec/controllers/supply_teachers/admin/frameworks_controller_spec.rb
spec/support/controller_macros.rb

Ticket: [FMR-1271](https://crowncommercialservice.atlassian.net/browse/FMFR-1271)
To make it easier to change the framework dates in production, i.e. without the need for a deployment, I have added the new role `ccs_developer` which gives limited access to change the framework dates.

FMFR-1271 - Allow special access to change framework dates

---

app/models/legal_services/journey/check_suitability.rb
app/models/legal_services/journey/select_lot.rb
app/models/legal_services/rm3788/journey/select_lot.rb
app/models/legal_services/rm6240/journey/check_suitability.rb
app/models/legal_services/rm6240/journey/select_lot.rb
app/models/legal_services/rm6240/lot.rb
app/views/legal_services/journey/_select_lot.html.erb
app/views/legal_services/rm6240/journey/check_suitability.html.erb
config/locales/views/legal_services.en.yml
spec/models/legal_services/rm3788/journey/select_lot_spec.rb
spec/models/legal_services/rm6240/journey/check_suitability_spec.rb
spec/models/legal_services/rm6240/journey/choose_organisation_type_spec.rb
spec/models/legal_services/rm6240/journey/select_lot_spec.rb

Tickets:
- [FMFR-1214](https://crowncommercialservice.atlassian.net/browse/FMFR-1214)
- [FMFR-1216](https://crowncommercialservice.atlassian.net/browse/FMFR-1215)
I have added the suitability option for when the buyer belongs to Central Government. I’ve also made an update to carry through the ‘Central government’ option so only the relevant lots and services are shown on later pages.

FMFR-1214 add suitability question for new framework

---

pipeline_pre_build_tests.sh

Update how we download PhantomJS for the tests that use it when deploying to the legacy applications.

Update how we download PhantomJS for the tests in AWS

---

features/services/supply_teachers/rm3826/journey/agency_results/fixed_term/daily_rate.feature
features/services/supply_teachers/rm6238/jounrey/agency_results/fixed_term/daily_rate.feature
features/step_definitions/supply_teachers_steps.rb

This fixes some issues with these tests which were failing on certain dates.
This is because on most dates the length of the contract used in this test would be 2.5 months. However, on some days (including today 30 August 20220, it would be calculated (correctly) as 3 months.
This change will make sure that the length is always 2.5 months on every day of the year.

This fixes some issues with these tests which were failing on certain dates.

---

app/controllers/supply_teachers/suppliers_controller.rb
app/helpers/supply_teachers/rm6238/shared_helper.rb
app/models/supply_teachers/rm6238/rate.rb
app/services/supply_teachers/rm6238/admin/data_import/generate_pricing.rb
app/views/supply_teachers/rm6238/shared/_rates_table.html.erb
data/supply_teachers/rm6238/dummy_supplier_data.json
data/supply_teachers/rm6238/job_types.csv
features/services/supply_teachers/rm6238/jounrey/all_agencies/suppliers.feature
features/services/supply_teachers/rm6238/jounrey/master_vendor/master_vendor_above_threshold.feature
features/services/supply_teachers/rm6238/jounrey/master_vendor/master_vendor_below_threshold.feature
spec/helpers/supply_teachers/rm6238/shared_helper_spec.rb
spec/models/supply_teachers/rm6238/rate_spec.rb

Ticket: [FMFR-1288](https://crowncommercialservice.atlassian.net/browse/FMFR-1288)
This change makes sure that the rates are shown in the right order (based on the role). In addition I’ve updated the ‘over_12_weeks’ role as this no longer has a term (this is a change from what was in the original pricing data given to us).
I have added/updated specs/features to reflect these changes

FMFR-1288 - Make sure the rates are sorted correctly by job role

---

app/models/supply_teachers/rm6238/supplier.rb
spec/models/supply_teachers/rm6238/supplier_spec.rb

Ticket: [FMFR-1289](https://crowncommercialservice.atlassian.net/browse/FMFR-1289)
When we get the grouped rates, we make sure we only select the rates belonging to lot 1.

FMFR-1289 - Make sure only lot 1 rates are shown

---

lib/tasks/frameworks.rake

Ticket: [FMFR-1294](https://crowncommercialservice.atlassian.net/browse/FMFR-1294)
I have updated the dates in the for supply teachers in the tool so they are accurate. This will mean if the `rake db:legacy_frameworks` command is run, it will make sure both the old and the new framework are in their correct states.
I’ve changed the ephesus on the old framework so that it is closed by default but open in tests. In a feature release we may want to remove the old framework, but I have left it as it is until that decision is made.

FMFR-1294 - Update the dates for the ST frameworks

---

app/helpers/application_helper.rb
app/helpers/supply_teachers/admin/uploads_helper.rb
app/models/legal_services/admin/upload.rb
app/views/legal_services/admin/uploads/index.html.erb
app/views/legal_services/admin/uploads/show.html.erb
app/views/management_consultancy/rm6187/admin/uploads/index.html.erb
app/views/management_consultancy/rm6187/admin/uploads/show.html.erb
app/views/supply_teachers/admin/uploads/_current_upload.html.erb
app/views/supply_teachers/admin/uploads/show.html.erb
db/migrate/20220929130611_fix_issue_with_ls_uploads.rb
db/schema.rb
spec/helpers/application_helper_spec.rb

Ticket: [FMFR-1308](https://crowncommercialservice.atlassian.net/browse/FMFR-1308)
Fix an issue where legal services documents could not be downloaded in the admin tool. As all three services download files in the same way, I have created a helper to format the url for the document download to avoid this error in the future.
I have added some specs for this method.

FMFR-1308 - Fix issue with document download in legal services

---

db/migrate/20220929130611_fix_issue_with_ls_uploads.rb
db/migrate/20221024121403_remove_unused_file_columns.rb
db/migrate/20221104103710_fix_issue_with_ls_uploads_again.rb
db/schema.rb

Ticket: [FMFR-1333](https://crowncommercialservice.atlassian.net/browse/FMFR-1333)
Due to an issue with the [legacy release 2.5.3](https://github.com/Crown-Commercial-Service/crown-marketplace-legacy/pull/470), the database migration did not work due to models being removed. This has meant the admin sections for MC, LS and ST are not working.
I have had to comment out the original migration as that will no longer work both due to the model being removed and an update to rails. I have then added a new migration which will fix the issue with the LS upload for real this time.
I have tested it locally and it works, we will not be able to test this in the lower environments.

FMFR-1333 - Fix issue with migration in Release 2.5.3

---

app/services/cognito/confirm_sign_up.rb
app/services/cognito/forgot_password.rb
spec/services/cognito/confirm_password_reset_spec.rb
spec/services/cognito/confirm_sign_up_spec.rb
spec/services/cognito/create_user_from_cognito_spec.rb
spec/services/cognito/forgot_password_spec.rb
spec/services/cognito/resend_confirmation_code_spec.rb
spec/services/cognito/respond_to_challenge_spec.rb
spec/services/cognito/sign_in_user_spec.rb
spec/services/cognito/sign_up_user_spec.rb
spec/services/cognito/update_user_spec.rb

Ticket: [FMFR-1360](https://crowncommercialservice.atlassian.net/browse/FMFR-1360)
I have made sure that the email is lowercased for the forgot password and confirm sign up routes (where the user has to enter an email).
In addition, I have refactored all of the cognito service unit tests.

FMFR-1360 - Make sure user entered emails are downcased

---

app/views/layouts/application.html.erb

I have turned off the Turbolink caching. I had not properly considered the effect of using turbolinks within the application. On the surface it seemed to be fine but there were some issues with caching and the back/forward buttons that I had not considered.
I may investigate using turbolink caching (or perhaps something similar) in a future update (see: [FMFR-1326](https://crowncommercialservice.atlassian.net/browse/FMFR-1362)).

Remove Turbolinks chaching

---

app/models/concerns/dateable.rb
spec/models/concerns/dateable_spec.rb

Ticket: [FMFR-1363](https://crowncommercialservice.atlassian.net/browse/FMFR-1363)
I’ve fixed an issue with the `Dateable` concern where it was not correctly counting half days properly. This bug meant that there were dates near the ends of the months where the `difference_in_months` was returning a larger value when the actual difference was smaller.
I’ve added specs for the concern (as there were not any) as well as fix the bug. This will also fix the issue with the feature tests.

FMFR-1363 - Fix issue with `Dateable` concern where `distance_in_months` were being miscalculated

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/base/sessions_controller.rb
app/views/base/sessions/new.html.erb
app/views/layouts/application.html.erb
config/initializers/ext.rb
config/locales/en.yml
config/routes.rb
lib/ext/ruby/auto_session_timeout_helper.rb
spec/controllers/base/sessions_controller_spec.rb

Ticket: [FMFR-1364](https://crowncommercialservice.atlassian.net/browse/FMFR-1364)
Add auto session timeout for legacy services
We need to also update load balancer to change the rule that says  `/legacy-storage*` to `/legacy*` as we need the auto timeout to hit the right server when it is making the calls.

FMFR-1364 - Add auto session timeout for legacy services

---

app/javascript/src/shared/cookieBanner.ts
app/javascript/src/shared/googleAnalyticsDataLayer.ts
config/application.rb
config/locales/en.yml
features/helpers/cookies_helper.rb
features/step_definitions/home_steps.rb
features/step_definitions/hooks.rb
spec/controllers/legal_services/rm6240/admin/uploads_controller_spec.rb
spec/controllers/legal_services/rm6240/home_controller_spec.rb
spec/controllers/management_consultancy/rm6187/admin/uploads_controller_spec.rb
spec/controllers/management_consultancy/rm6187/home_controller_spec.rb
spec/controllers/supply_teachers/rm6238/admin/uploads_controller_spec.rb
spec/controllers/supply_teachers/rm6238/home_controller_spec.rb
spec/helpers/application_helper_spec.rb
spec/views/layouts/application.html.erb_spec.rb

Because the cookie_preferences is set by the corporate website which has the .crowncommercial.gov.uk, it will supersede any cookie we set as Crown Marketplace is hosted on a subdomain. Therefore, I have renamed the cookie to remove this conflict.

Rename `cookie_preferences` cookie to `cookie_preferences_cmp` so that it does not conflict with corporate website

---

.env.test
app/controllers/home_controller.rb
app/views/home/status.html.erb
config/environments/production.rb
config/routes.rb
spec/controllers/home_controller_spec.rb

This is so the ECS tasks can check for the health of the container (it is currently being blocked)
The health check path needs to be updated to: `/legacy-healthcheck`

Update the healthcheck route to check for the apps status
