Crown-Commercial-Service/crown-marketplace-legacy

app/controllers/supply_teachers/suppliers_controller.rb
app/views/layouts/application.html.erb

Also set up correct back path for ST

Remove h1 with legacy

---

app/controllers/home_controller.rb
app/helpers/application_helper.rb
app/views/home/accessibility/_accessibility_statement.html.erb
app/views/home/accessibility/_not_in_scope.html.erb
app/views/home/accessibility/_preparation_for_audit.html.erb
app/views/home/accessibility/_shared_section.html.erb
app/views/home/accessibility_statement_ls.html.erb
app/views/home/accessibility_statement_mc.html.erb
app/views/home/accessibility_statement_st.html.erb
app/views/layouts/_footer.html.erb
config/locales/en.yml
config/routes.rb

> - Create route for the accessibility statement
> - Create the accessibility page
> - Put shared parts of statement in partials
> - Put more sections in partials
> - Finish adding the shared parts

CSI-180 ST Accessibility Statement

---

app/controllers/supply_teachers/suppliers_controller.rb
app/models/supply_teachers/journey/looking_for.rb
app/views/supply_teachers/journey/looking_for.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/supply_teachers/journey_controller_spec.rb
spec/controllers/supply_teachers/suppliers_controller_spec.rb
spec/features/supply_teachers/managed_service_providers.features_spec.rb

Applying changes from crown-marketplace

Removed neutral vendors option

---

spec/features/supply_teachers/managed_service_providers.features_spec.rb

As neutral vendors page and option do not exist anymore

Removed redundant test

---

app/helpers/management_consultancy/suppliers_helper.rb
app/views/management_consultancy/suppliers/download.html.erb
config/locales/en.yml

> - Make sure each service links to correct eoi doc

CSI-197 - Update EOI documents for MC 

---

lib/tasks/legal_services/data.rake
lib/tasks/management_consultancy/data.rake

> - Create task to anonymise LS supplier data
> - Add task to anonymise MC data

Create tasks to anonymise MC and LS data for non-prod environments

---

app/helpers/legal_services/suppliers_helper.rb
app/views/legal_services/suppliers/show.html.erb
lib/tasks/legal_services/data.rake
spec/helpers/legal_services/suppliers_helper_spec.rb

<details>
<summary> Commits </summary>
<ul>
<li>Create helpers for the prospectus link</li>
<li>Add tests for the new helper methods</li>
</ul>
</details>

FMFR-523 - Fix issue when prospectus link is text

---

app/helpers/legal_services/suppliers_helper.rb
app/views/legal_services/suppliers/show.html.erb
lib/tasks/legal_services/data.rake
lib/tasks/legal_services/scripts/add_rate_cards_to_suppliers.rb
spec/helpers/legal_services/suppliers_helper_spec.rb

> - Update view to show pence
> - Update task to make some prices decimal
> - Add tests for displaying rate with pounds and pence

FMFR-532 - Show pounds and pence for LS rates

---

Gemfile.lock

FMFR-726 - update mimemagic gem to newer version

---

app/workers/supply_teachers/data_upload_worker.rb

FMFR-784 - Update so that the ST upload works

---

app/controllers/management_consultancy/suppliers_controller.rb
app/helpers/management_consultancy/suppliers_helper.rb
app/models/management_consultancy/journey/choose_lot.rb
app/models/management_consultancy/journey/choose_services.rb
app/services/management_consultancy/supplier_spreadsheet_creator.rb
app/views/management_consultancy/journey/_management_consultancy_lots.html.erb
app/views/management_consultancy/journey/choose_lot.html.erb
config/application.rb
config/locales/en.yml
data/management_consultancy/lots.csv
data/management_consultancy/services.csv
lib/tasks/management_consultancy/scripts/add_rate_cards_to_suppliers.rb
lib/tasks/management_consultancy/scripts/add_region_availability_per_lot_per_supplier.rb
lib/tasks/management_consultancy/scripts/add_service_offerings_per_supplier.rb
lib/tasks/management_consultancy/scripts/add_suppliers.rb
spec/controllers/management_consultancy/suppliers_controller_spec.rb
spec/factories/management_consultancy_supplier.rb
spec/features/authentication.feature_spec.rb
spec/features/management_consultancy/management_consultancy.feature_spec.rb
spec/models/management_consultancy/lot_spec.rb
spec/models/management_consultancy/service_spec.rb

> - Remove the need for regions
> - Update to have a cut-off date
> - Add mcf3 data on top of other fw
> - Update tests to account for go live
> - Add tests for MCF3 scenarios
The following environment variable needs to be added:
`/Environment/global/MCF3_LIVE_DATE=2021/09/04`

FMFR-702 - Complete work to add MCF3

---

app/services/cognito/sign_up_user.rb
config/locales/en.yml
spec/services/cognito/sign_up_user_spec.rb

- Add validation for number and email case

FMFR-870 - Add validation for number and email case

---

app/helpers/application_helper.rb
app/views/layouts/_phase-banner-end-of-journey.html.erb
config/application.rb

- Show the survey link
The following environment variable needs to be created:
`/Environment/ccs/cmp-legacy/ST_SURVEY_LINK=https://crowncommercial.qualtrics.com/jfe/form/SV_2lvdOWaM7JKdqJw`
`/Environment/ccs/cmp-legacy/LS_SURVEY_LINK=https://crowncommercial.qualtrics.com/jfe/form/SV_cO7ru7EJJ43EvGK`

FMFR-872 - Update the survey links

---

app/models/allowed_email_domain.rb
app/services/cognito/sign_up_user.rb
spec/services/cognito/sign_up_user_spec.rb

- Make sure the allow list domain validation is case insensitive

FMFR-890 - Ignore case of email domain

---

app/models/concerns/supply_teachers/contract_startable.rb
app/models/concerns/supply_teachers/date_validator.rb
app/models/supply_teachers/journey/fixed_term_results.rb
app/models/supply_teachers/journey/fta_calculator_contract_end.rb
app/models/supply_teachers/journey/fta_calculator_contract_start.rb
app/models/supply_teachers/journey/fta_to_perm_contract_end.rb
app/models/supply_teachers/journey/fta_to_perm_contract_start.rb
app/models/supply_teachers/journey/fta_to_perm_fixed_term_fee.rb
app/models/supply_teachers/journey/fta_to_perm_hire_date.rb
app/models/supply_teachers/journey/temp_to_perm_calculator.rb

> - Update the date validation
> - Add a concern for the dates
> - Add all the date validations into concern

Improve code maintainability by refactoring date validation

---

app/calculators/fta_to_perm_calculator/calculator.rb
app/calculators/temp_to_perm_calculator/calculator.rb
app/helpers/supply_teachers/temp_to_perm_calculator_helper.rb
app/services/working_days.rb
spec/calculators/temp_to_perm_calculator/calculator_spec.rb

- Move the working days out of the calculator into own class

Improve code maintainability by moving working days from calculator into own class

---

Gemfile
Gemfile.lock
app/views/supply_teachers/gateway/index.html.erb
config/routes.rb

- Update gem version and refactor for changes

FMFR-1014 - update gems to be compatible with `omniauth v2`

---

config/locales/en.yml

[FMFR-122](https://crowncommercialservice.atlassian.net/browse/FMFR-1122)
Changed the wording from "Sign in with Cognito" to "Sign in with CCS".

FMFR-1122 - Change wording on sign in page

---

pipeline_pre_build_tests.sh

- Update the node version for the pipeline to v14 (This is the next oldest LTS version)
This should fix the issue with some of the deployments

Update the node version for the pipeline to v14

---

spec/models/supply_teachers/admin/upload_spec.rb

- Make sure all files are unique when created and not shared between any attribute
- Change how we create the object to make sure files are created
- Change how the new upload object is created and tested

Make changes to try and fix flakey tests

---

app/helpers/gov_uk_helper/header.rb
app/views/layouts/application.html.erb
app/views/layouts/error.html.erb
features/helpers/responsive_headers_helper.rb
features/services/legal_services/responsive_navigation_links.feature
features/services/management_consultancy/responsive_navigation_links.feature
features/services/supply_teachers/responsive_navigation_links.feature
features/step_definitions/home_steps.rb
features/step_definitions/hooks.rb
features/support/pages/home_page.rb

Make some small updates to fix some issues with GOV.UK Frontend. This includes:
- Fix issue with the header
- Add JS to skip link to improve accessibility
I also added to test to check the Javascript

Make some small updates to fix some issues with GOV.UK Frontend

---

app/models/management_consultancy/journey.rb
app/models/management_consultancy/rm6187/journey/improvements.rb
app/views/management_consultancy/rm6187/journey/improvements.html.erb
config/locales/views/management_consultancy.en.yml
features/accessibility/management_consultancy/rm6187/journey/improvements_accessibility.feature
features/accessibility/management_consultancy/rm6187/journey/service_selection_accessibility.feature
features/accessibility/management_consultancy/rm6187/journey/suppliers_accessibility.feature
features/services/management_consultancy/rm6187/home/start_pages.feature
features/services/management_consultancy/rm6187/journey/results/lot_1.feature
features/services/management_consultancy/rm6187/journey/results/lot_2.feature
features/services/management_consultancy/rm6187/journey/results/lot_3.feature
features/services/management_consultancy/rm6187/journey/results/lot_4.feature
features/services/management_consultancy/rm6187/journey/results/lot_5.feature
features/services/management_consultancy/rm6187/journey/results/lot_6.feature
features/services/management_consultancy/rm6187/journey/results/lot_7.feature
features/services/management_consultancy/rm6187/journey/results/lot_8.feature
features/services/management_consultancy/rm6187/journey/results/lot_9.feature
features/services/management_consultancy/rm6187/journey/service_selection/lot_1.feature
features/services/management_consultancy/rm6187/journey/service_selection/lot_2.feature
features/services/management_consultancy/rm6187/journey/service_selection/lot_3.feature
features/services/management_consultancy/rm6187/journey/service_selection/lot_4.feature
features/services/management_consultancy/rm6187/journey/service_selection/lot_5.feature
features/services/management_consultancy/rm6187/journey/service_selection/lot_6.feature
features/services/management_consultancy/rm6187/journey/service_selection/lot_7.feature
features/services/management_consultancy/rm6187/journey/service_selection/lot_8.feature
features/services/management_consultancy/rm6187/journey/service_selection/lot_9.feature
features/services/management_consultancy/rm6187/journey/suppliers.feature
features/services/management_consultancy/rm6187/journey/validations/journey_validations.feature
features/step_definitions/common_steps.rb
spec/features/authentication.feature_spec.rb

Ticket: [FMFR-1200](https://crowncommercialservice.atlassian.net/browse/FMFR-1200)
Add the 'Improvements to CCS digital solutions' which informs users about PPG when they log in.
Also updated any tests that this change initially broke.

FMFR-1200 - Add 'Improvements to CCS digital solutions' page

---

data/supply_teachers/rm6238/dummy_supplier_data.json
features/accessibility/supply_teachers/rm6238/journey/agency_results_accessibility.feature
features/services/supply_teachers/rm6238/jounrey/agency_results/agency_payroll/results_by_length.feature
features/services/supply_teachers/rm6238/jounrey/agency_results/agency_payroll/results_by_location.feature
features/services/supply_teachers/rm6238/jounrey/agency_results/agency_payroll/results_by_role.feature
features/services/supply_teachers/rm6238/jounrey/agency_results/agency_payroll/suppliers.feature
features/services/supply_teachers/rm6238/jounrey/agency_results/fixed_term/daily_rate.feature
features/services/supply_teachers/rm6238/jounrey/agency_results/fixed_term/results_by_length.feature
features/services/supply_teachers/rm6238/jounrey/agency_results/fixed_term/results_by_location.feature
features/services/supply_teachers/rm6238/jounrey/agency_results/fixed_term/results_by_salary.feature
features/services/supply_teachers/rm6238/jounrey/agency_results/fixed_term/suppliers.feature
features/services/supply_teachers/rm6238/jounrey/agency_results/nominated_worker/results_by_location.feature
features/services/supply_teachers/rm6238/jounrey/agency_results/nominated_worker/suppliers.feature
features/services/supply_teachers/rm6238/jounrey/managed_service_provider/education_technology_platforms.feature
features/services/supply_teachers/rm6238/jounrey/managed_service_provider/master_vendor_above_threshold.feature
features/services/supply_teachers/rm6238/jounrey/managed_service_provider/master_vendor_below_threshold.feature
features/services/supply_teachers/rm6238/jounrey/validations/agency_results/fixed_term_validation.feature
features/services/supply_teachers/rm6238/jounrey/validations/agency_results_validations.feature
lib/tasks/generate_test_data/rm6238/st.rake

In this commit I have added the feature tests for the agency results section of the new Supply Teachers framework.

Add feature tests for  agency results

---

app/controllers/supply_teachers/rm3826/suppliers_controller.rb
app/controllers/supply_teachers/rm6238/suppliers_controller.rb
app/controllers/supply_teachers/suppliers_controller.rb
app/models/supply_teachers/rm6238/journey/all_suppliers.rb
app/models/supply_teachers/rm6238/journey/looking_for.rb
app/views/supply_teachers/suppliers/_branch.html.erb
app/views/supply_teachers/suppliers/all_suppliers.html.erb
config/locales/views/supply_teachers.en.yml
config/routes.rb
features/accessibility/supply_teachers/rm6238/journey/all_agencies_accessibility.feature
features/services/supply_teachers/rm6238/jounrey/all_agencies/results.feature
features/services/supply_teachers/rm6238/jounrey/all_agencies/suppliers.feature
features/step_definitions/supply_teachers_steps.rb
spec/controllers/supply_teachers/rm6238/suppliers_controller_spec.rb
spec/models/supply_teachers/rm6238/journey/looking_for_spec.rb
spec/views/supply_teachers/rm3826/suppliers/_branch.html.erb_spec.rb
spec/views/supply_teachers/rm3826/suppliers/all_suppliers.html.erb_spec.rb

Ticket: [FMR-1261](https://crowncommercialservice.atlassian.net/browse/FMFR-1261)
Added the all suppliers section for the new framework.
Added specs and feature test for this section.

FMFR-1261 - Add the all suppliers section

---

app/controllers/legal_services/rm6240/home_controller.rb
app/controllers/legal_services/rm6240/passwords_controller.rb
app/controllers/legal_services/rm6240/registrations_controller.rb
app/controllers/legal_services/rm6240/sessions_controller.rb
app/controllers/legal_services/rm6240/users_controller.rb
app/views/legal_services/rm6240/home/index.html.erb
config/locales/views/legal_services.en.yml
config/routes.rb
spec/controllers/legal_services/rm6240/passwords_controller_spec.rb
spec/controllers/legal_services/rm6240/registrations_controller_spec.rb
spec/controllers/legal_services/rm6240/sessions_controller_spec.rb
spec/controllers/legal_services/rm6240/users_controller_spec.rb

Ticket: [FMR-1273](https://crowncommercialservice.atlassian.net/browse/FMFR-1273)
Add the authentication and registration section in the new legal service framework

FMFR-1273 - Add login for now LS framework

---

app/models/legal_services/rm6240/journey/sorry.rb
app/views/legal_services/rm6240/journey/sorry.html.erb
config/locales/en.yml
config/locales/views/legal_services.en.yml
spec/models/legal_services/rm6240/journey/check_suitability_spec.rb
spec/models/legal_services/rm6240/journey/sorry_spec.rb

Ticket: [FMFR-1215](https://crowncommercialservice.atlassian.net/browse/FMFR-1215)
Add the 'sorry' panel for the new framework

FMFR-1215 - Add the 'sorry' panel for the new framework

---

app/models/legal_services/journey/check_suitability.rb
app/services/legal_services/rm3788/supplier_spreadsheet_creator.rb
app/services/legal_services/rm6240/supplier_spreadsheet_creator.rb
app/services/legal_services/supplier_spreadsheet_creator.rb
app/services/supplier_spreadsheet_creator.rb
app/views/legal_services/suppliers/download.html.erb
data/legal_services/rm6240/services.csv
spec/controllers/legal_services/rm6240/suppliers_controller_spec.rb
spec/services/legal_services/rm3788/supplier_spreadsheet_creator_spec.rb
spec/services/legal_services/rm6240/supplier_spreadsheet_creator_spec.rb

Ticket: [FMFR-1213](https://crowncommercialservice.atlassian.net/browse/FMFR-1213)
In this commit I have added the ability for the spreadsheet to be downloaded.
This spreadsheet shows the results from the buyer's search.
As this spreadsheet is very similar to the previous framework I've been able to share code as much as possible.

FMFR - 1213 - Add supplier spreadsheet download

---

app/controllers/legal_services/framework_controller.rb
app/controllers/management_consultancy/framework_controller.rb
app/controllers/supply_teachers/framework_controller.rb

This prevents an infinite loop occuring

Make sure unrecognised framework is at the top of the call backs

---

app/assets/stylesheets/components/header/_header.scss
app/helpers/gov_uk_helper/header.rb

Make small change to the header component and scss to fix some issues.
This fixes an issue with the focus on the header link not being correct:

Make small change to the header component and scss to fix some issues

---

app/models/legal_services/journey/select_lot.rb
app/models/legal_services/rm3788/journey/select_lot.rb
app/models/legal_services/rm6240/journey/choose_services.rb
app/models/legal_services/rm6240/journey/select_lot.rb
app/models/legal_services/rm6240/lot.rb
app/models/legal_services/rm6240/service.rb
app/views/legal_services/journey/_choose_services.html.erb
app/views/legal_services/journey/_select_lot.html.erb
data/legal_services/rm6240/services.csv
features/accessibility/legal_services/rm6240/journey/suppliers_accessibility.feature
features/services/legal_services/rm3788/journey/non_central_government/lot_1/restults.feature
features/services/legal_services/rm3788/journey/non_central_government/lot_2/restults.feature
features/services/legal_services/rm6240/journey/central_government/lot_1/service_selection.feature
features/services/legal_services/rm6240/journey/central_government/lot_2/service_selection.feature
features/services/legal_services/rm6240/journey/central_government/lot_3/suppliers.feature
features/services/legal_services/rm6240/journey/non_central_government/lot_1/restults.feature
features/services/legal_services/rm6240/journey/non_central_government/lot_1/suppliers.feature
features/services/legal_services/rm6240/journey/non_central_government/lot_2/restults.feature
features/services/legal_services/rm6240/journey/non_central_government/lot_2/suppliers.feature
spec/models/legal_services/rm3788/journey/select_lot_spec.rb
spec/models/legal_services/rm6240/journey/choose_services_spec.rb
spec/models/legal_services/rm6240/journey/select_lot_spec.rb
spec/models/legal_services/rm6240/service_spec.rb

Ticket: [FMFR-1281](https://crowncommercialservice.atlassian.net/browse/FMFR-1281)
We do not need to restrict the lot and service selection for when the user selects the central government so I have removed the restriction.
I have also updated the specs and feature tests to account for the changes.

FMFR-1281 - Remove central government restrictions

---

app/controllers/supply_teachers/branches_controller.rb
app/services/supply_teachers/rm3826/spreadsheet.rb
app/services/supply_teachers/rm6238/spreadsheet.rb
app/services/supply_teachers/spreadsheet.rb
spec/services/supply_teachers/rm3826/spreadsheet_spec.rb
spec/services/supply_teachers/rm6238/spreadsheet_spec.rb

Ticket: [FMFR-1278](https://crowncommercialservice.atlassian.net/browse/FMFR-1278)
Update the spreadsheet creator for Supply Teachers.
We will now show the supplier distance and the supplier fee along with the other information

FMFR-1278 - Add supplier fee to the spreadsheet

---

features/services/legal_services/rm6240/journey/central_government/lot_3/suppliers.feature

This fixes some issues which broke some tests.

Change the copy from daily to hourly

---

app/views/supply_teachers/branches/index.html.erb
app/views/supply_teachers/rm6238/home/index.html.erb
app/views/supply_teachers/rm6238/suppliers/_what_to_do_next.html.erb
app/views/supply_teachers/rm6238/suppliers/education_technology_platform_vendors.html.erb
app/views/supply_teachers/rm6238/suppliers/master_vendors.html.erb
config/locales/views/supply_teachers.en.yml
features/accessibility/supply_teachers/rm6238/journey/education_technology_platforms_accessibility.feature
features/accessibility/supply_teachers/rm6238/journey/master_vendor_providers_accessibility.feature
features/services/supply_teachers/rm6238/jounrey/education_technology_platforms/education_technology_platforms.feature
features/services/supply_teachers/rm6238/jounrey/master_vendor/master_vendor_above_threshold.feature
features/services/supply_teachers/rm6238/jounrey/master_vendor/master_vendor_below_threshold.feature
features/services/supply_teachers/rm6238/jounrey/validations/master_vendor_validations.feature

Ticket: [FMFR-1264](https://crowncommercialservice.atlassian.net/browse/FMFR-1264)
Update the copy the new ST framework on the following pages:
- Update the start page copy
- Update the looking for page
- Add threshold hint
- Update what to do next for lot 1
- Update what to do next for lot 2 and 4

FMFR-1264 - Update the copy the new ST framework

---

data/supply_teachers/rm6238/job_types.csv
features/services/supply_teachers/rm6238/jounrey/all_agencies/suppliers.feature
features/services/supply_teachers/rm6238/jounrey/education_technology_platforms/education_technology_platforms.feature
features/services/supply_teachers/rm6238/jounrey/master_vendor/master_vendor_above_threshold.feature
features/services/supply_teachers/rm6238/jounrey/master_vendor/master_vendor_below_threshold.feature

Ticket: [FMFR-1287](https://crowncommercialservice.atlassian.net/browse/FMFR-1287)

Update the copy for some of the ST Job types

---

app/views/supply_teachers/suppliers/all_suppliers.html.erb
config/locales/views/supply_teachers.en.yml
features/accessibility/supply_teachers/rm3826/journey/all_agencies_accessibility.feature
features/accessibility/supply_teachers/rm6238/journey/all_agencies_accessibility.feature
features/services/supply_teachers/rm3826/journey/all_agencies/results.feature
features/services/supply_teachers/rm3826/journey/all_agencies/suppliers.feature
features/services/supply_teachers/rm6238/jounrey/all_agencies/results.feature
features/services/supply_teachers/rm6238/jounrey/all_agencies/suppliers.feature
features/support/pages/supply_teachers_page.rb
spec/views/supply_teachers/suppliers/all_suppliers.html.erb_spec.rb

Ticket: [FMFR-1285](https://crowncommercialservice.atlassian.net/browse/FMFR-1285)

FMFR-1285 - Update the copy for the all agencies page

---

app/assets/javascripts/application.js
app/controllers/concerns/cookie_settings_concern.rb
app/helpers/application_helper.rb
app/typescript/shared/cookieBanner.ts
package.json
spec/helpers/application_helper_spec.rb
yarn.lock

Ticket: [FMFR-1310](https://crowncommercialservice.atlassian.net/browse/FMFR-1310)
Fix an issue where cookie is not removed when JS is enabled due to GA creating the cookie when the website is reloaded

FMFR-1310 - Fix issue where cookie is not deleted properly

---

app/controllers/auth_controller.rb
spec/controllers/auth_controller_spec.rb

Ticket: [FMFR-1313](https://crowncommercialservice.atlassian.net/browse/FMFR-1313)
Fix issue with DfE login caused by emails not being all lower case

FMFR-1313 - Fix issue with DfE login

---

app/models/ability.rb

Ticket: [FMFR-1306](https://crowncommercialservice.atlassian.net/browse/FMFR-1306)
Update the ability config to better reflect the abilities different roles should have.

FMFR-1306 - Refactor ability so roles match better

---

app/services/legal_services/rm6240/admin/files_processor.rb
spec/support/legal_services/rm6240/admin/file_importer_helper.rb

Ticket: [FMFR-1330](https://crowncommercialservice.atlassian.net/browse/FMFR-1330)
Fix issue with import for legal services by calling the method safely

FMFR-1330 - Fix issue with LS upload

---

features/services/supply_teachers/rm6238/jounrey/fta_to_perm/journeys.feature
features/step_definitions/supply_teachers_steps.rb

Make sure the dates for the test are correct when the ends of the months do not align

Fix flakey test

---

config/locales/views/legal_services.en.yml

Ticket: [FMFR-1307](https://crowncommercialservice.atlassian.net/browse/FMFR-1307)

Reworded Extended descriptions (FMFR-1307)

---

app/services/cognito/sign_in_user.rb
app/services/cognito/sign_up_user.rb
features/services/legal_services/rm6240/cognito/validations/sign_in_validation.feature
features/services/management_consultancy/rm6187/cognito/validations/sign_in_validation.feature
features/services/supply_teachers/rm6238/cognito/validations/sign_in_validation.feature
spec/services/cognito/sign_in_user_spec.rb
spec/services/cognito/sign_up_user_spec.rb

Same changes as were made in crown marketplace

Changes to sign up & sign in validation

---

app/views/management_consultancy/rm6187/journey/important_changes.html.erb
config/locales/views/management_consultancy.en.yml

Ticket: [FMFR-1339](https://crowncommercialservice.atlassian.net/browse/FMFR-1339)
Update the text on the important information page for MCF3

FMFR-1339 - Update the text for MCF3

---

app/views/management_consultancy/rm6187/journey/important_changes.html.erb
config/locales/views/management_consultancy.en.yml

Ticket: [FMFR-1339](https://crowncommercialservice.atlassian.net/browse/FMFR-1339)

FMFR-1339 - Add missing line

---

app/views/supply_teachers/admin/uploads/show.html.erb
config/locales/views/legal_services.en.yml
config/locales/views/supply_teachers.en.yml

Fix some typos I find while doing https://github.com/tim-s-ccs/crown-marketplace-legacy-feature-tests/pulls

Fix some typos I found while doing feature tests

---

app/assets/stylesheets/components/_all.scss
app/assets/stylesheets/components/notification-banner/_notification-banner.scss
app/helpers/application_helper.rb
app/helpers/gov_uk_helper/notification_banner.rb
app/helpers/supply_teachers/admin/uploads_helper.rb
app/javascript/.eslintrc.json
app/javascript/packs/application.js
app/javascript/src/shared/adminUpload.ts
app/javascript/src/shared/basket.ts
app/javascript/src/shared/cookieBanner.ts
app/javascript/src/shared/googleAnalytics.ts
app/javascript/src/shared/passwordStrength.ts
app/javascript/src/shared/uploadProgress.ts
app/javascript/src/supplyTeachers/adminUpload.ts
app/javascript/src/supplyTeachers/supplierMarkupCalculator.ts
app/views/home/cookie_settings.html.erb
app/views/layouts/_cookie-banner.html.erb
config/locales/en.yml
package.json
yarn.lock

Now that we have got webpack working and I have set up the TypeScript how I want it, I have decided to use standard typescript linting to maintain the quality of our TypeScript.

Use `standard-with-typescript` for linting

---

app/services/cognito/confirm_password_reset.rb
app/services/cognito/resend_confirmation_code.rb
spec/services/cognito/confirm_password_reset_spec.rb
spec/services/cognito/confirm_sign_up_spec.rb
spec/services/cognito/create_user_from_cognito_spec.rb
spec/services/cognito/forgot_password_spec.rb
spec/services/cognito/resend_confirmation_code_spec.rb
spec/services/cognito/respond_to_challenge_spec.rb
spec/services/cognito/sign_in_user_spec.rb
spec/services/cognito/sign_up_user_spec.rb
spec/services/cognito/update_user_spec.rb

Ticket: [FMFR-1360](https://crowncommercialservice.atlassian.net/browse/FMFR-1360)
Make sure anywhere where we except emails to send emails, we make the email downcase

FMFR-1360 - Make sure emails are downcased

---

TAGS

Remove TAGS file, I am not sure why it exists in the first place

Remove TAGS file

---

app/controllers/legal_services/rm6240/suppliers_controller.rb
app/models/legal_services/rm6240/supplier.rb
features/services/legal_services/rm6240/journey/central_government/lot_1/supplier_rates.feature
features/services/legal_services/rm6240/journey/central_government/lot_2/supplier_rates.feature
features/services/legal_services/rm6240/journey/central_government/lot_2/suppliers.feature
features/services/legal_services/rm6240/journey/non_central_government/lot_1/supplier_rates.feature
features/services/legal_services/rm6240/journey/non_central_government/lot_1/suppliers.feature
features/services/legal_services/rm6240/journey/non_central_government/lot_2/supplier_rates.feature
spec/models/legal_services/rm6240/supplier_spec.rb

Ticket: [FMFR-1374](https://crowncommercialservice.atlassian.net/browse/FMFR-1374)
The Legal Services category found an issue with the rates with respect to jurisdiction. In this ticket I have fixed this issue and added tests to make sure my changes work.

FMFR-1374 - LS rates issue

---

config/locales/views/management_consultancy.en.yml

Ticket: [FMFR-1384](https://crowncommercialservice.atlassian.net/browse/FMFR-1384)
**Description:**
Update the copy on the page

FMFR-1384 - Update the copy on the page

---

config/initializers/omniauth_dfe.rb

Ticket: [FMFR-1391](https://crowncommercialservice.atlassian.net/browse/FMFR-1391)
Add the Issuer URL for the webfinger

FMFR-1391 - Add the Issuer URL for the webfinger

---

config/locales/en.yml

Ticket: [FMFR-1397](https://crowncommercialservice.atlassian.net/browse/FMFR-1397)

FMFR-1397 - Update email from support@ to the correct info@

---

data/management_consultancy/rm6309/dummy_supplier_data.json
lib/tasks/generate_test_data/mc/rm6309.rake
lib/tasks/import_test_data.rake

Ticket: [NDF-11](https://crowncommercialservice.atlassian.net/browse/NDF-11)

NDF-11 - Create the test data for MCF4

---

app/models/management_consultancy/rm6309/admin/upload.rb
app/models/management_consultancy/rm6309/lot_contact_detail.rb
app/models/management_consultancy/rm6309/rate_card.rb
app/models/management_consultancy/rm6309/service_offering.rb
app/models/management_consultancy/rm6309/supplier.rb
app/models/management_consultancy/rm6309/upload.rb
app/workers/management_consultancy/rm6309/admin/file_upload_worker.rb
config/locales/views/management_consultancy.en.yml
data/management_consultancy/rm6309/dummy_supplier_data.json
lib/tasks/generate_test_data/mc/rm6309.rake
lib/tasks/import_test_data.rake
spec/factories/management_consultancy/rm6309/admin/upload.rb
spec/factories/management_consultancy/rm6309/lot_contact_detail.rb
spec/factories/management_consultancy/rm6309/rate_card.rb
spec/factories/management_consultancy/rm6309/service_offering.rb
spec/factories/management_consultancy/rm6309/supplier.rb
spec/models/management_consultancy/rm6309/admin/upload_spec.rb
spec/models/management_consultancy/rm6309/lot_contact_detail_spec.rb
spec/models/management_consultancy/rm6309/rate_card_spec.rb
spec/models/management_consultancy/rm6309/service_offering_spec.rb
spec/models/management_consultancy/rm6309/supplier_spec.rb
spec/models/management_consultancy/rm6309/upload_spec.rb

Ticket: [NDF-10](https://crowncommercialservice.atlassian.net/browse/NDF-10)

NDF-10 - Add MCF4 Models

---

app/models/management_consultancy/rm6309.rb
app/models/management_consultancy/rm6309/admin/upload.rb
app/models/management_consultancy/rm6309/lot.rb
app/models/management_consultancy/rm6309/lot_contact_detail.rb
app/models/management_consultancy/rm6309/rate_card.rb
app/models/management_consultancy/rm6309/service.rb
app/models/management_consultancy/rm6309/service_offering.rb
app/models/management_consultancy/rm6309/supplier.rb
app/models/management_consultancy/rm6309/upload.rb
app/workers/management_consultancy/rm6309/admin/file_upload_worker.rb
config/initializers/inflections.rb
config/locales/views/management_consultancy.en.yml
data/management_consultancy/rm6309/dummy_supplier_data.json
data/management_consultancy/rm6309/lots.csv
data/management_consultancy/rm6309/services.csv
lib/tasks/generate_test_data/mc/rm6309.rake
lib/tasks/import_test_data.rake
spec/factories/management_consultancy/rm6309/admin/upload.rb
spec/factories/management_consultancy/rm6309/lot_contact_detail.rb
spec/factories/management_consultancy/rm6309/rate_card.rb
spec/factories/management_consultancy/rm6309/service_offering.rb
spec/factories/management_consultancy/rm6309/supplier.rb
spec/models/management_consultancy/rm6309/admin/upload_spec.rb
spec/models/management_consultancy/rm6309/lot_contact_detail_spec.rb
spec/models/management_consultancy/rm6309/lot_spec.rb
spec/models/management_consultancy/rm6309/rate_card_spec.rb
spec/models/management_consultancy/rm6309/service_offering_spec.rb
spec/models/management_consultancy/rm6309/service_spec.rb
spec/models/management_consultancy/rm6309/supplier_spec.rb
spec/models/management_consultancy/rm6309/upload_spec.rb

Ticket: [NDF-9](https://crowncommercialservice.atlassian.net/browse/NDF-9)

NDF-9 - Add the service and lot models

---

lib/tasks/frameworks.rake

Reverts Crown-Commercial-Service/crown-marketplace-legacy#1895

Revert "Add a temp date change to make new MCF Framework live"

---

app/models/management_consultancy/rm6309/journey/choose_services.rb
app/views/management_consultancy/rm6309/suppliers/download.html.erb
config/locales/views/management_consultancy.en.yml
data/management_consultancy/rm6309/services.csv
features/services/management_consultancy/rm6309/journey/service_selection/lot_1.feature
features/services/management_consultancy/rm6309/journey/service_selection/lot_10.feature
features/services/management_consultancy/rm6309/journey/service_selection/lot_2.feature
features/services/management_consultancy/rm6309/journey/service_selection/lot_3.feature
features/services/management_consultancy/rm6309/journey/service_selection/lot_4.feature
features/services/management_consultancy/rm6309/journey/service_selection/lot_6.feature
features/services/management_consultancy/rm6309/journey/service_selection/lot_7.feature
features/services/management_consultancy/rm6309/journey/service_selection/lot_8.feature
features/services/management_consultancy/rm6309/journey/service_selection/lot_9.feature

Tickets:
- [NDF-41](https://crowncommercialservice.atlassian.net/browse/NDF-41)
- [NDF-43](https://crowncommercialservice.atlassian.net/browse/NDF-43)
- [NDF-44](https://crowncommercialservice.atlassian.net/browse/NDF-44)
- [NDF-45](https://crowncommercialservice.atlassian.net/browse/NDF-45)
- [NDF-46](https://crowncommercialservice.atlassian.net/browse/NDF-46)
- [NDF-47](https://crowncommercialservice.atlassian.net/browse/NDF-47)
- [NDF-53](https://crowncommercialservice.atlassian.net/browse/NDF-53)

Make a few small updates for MCF4
